import { League_Spartan } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
const league_spartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthContextProvider>
      <html lang="en">
        <body className={league_spartan.className}>{children}</body>
      </html>
    </AuthContextProvider>
  );
}
